In [9]:
import requests
import pandas as pd
import numpy as np
import geopy.distance

url = "https://www.zabka.pl/app/uploads/locator-store-data.json"
response = requests.get(url)

df = pd.DataFrame.from_dict(response.json())
df = df[df['town'] == "Łódź"]
df = df[['lat', 'lon']]
df['lat'] = df['lat'].astype(float)
df['lon'] = df['lon'].astype(float)



In [10]:
df.head()

lat        lon
112  51.774197  19.449903
167  51.732719  19.474108
168  51.728607  19.470244
188  51.766224  19.449934
216  51.763390  19.469598

In [12]:
distance_matrix = np.empty((len(df), len(df)))

for i1 in range(len(df)):
    for i2 in range(len(df)):
        point1 = (df.iloc[i1]['lat'], df.iloc[i1]['lon'])
        point2 = (df.iloc[i2]['lat'], df.iloc[i2]['lon'])
        
        d = geopy.distance.geodesic(point1, point2).mi
        distance_matrix[i1, i2] = d
        distance_matrix[i2, i1] = d

In [13]:
print(distance_matrix)

[[0.         3.04988791 3.27050721 ... 1.60627712 4.33123192 1.54798574]
 [3.04988791 0.         0.3291415  ... 4.64813222 1.28134574 1.5529183 ]
 [3.27050721 0.3291415  0.         ... 4.85505901 1.099363   1.73850483]
 ...
 [1.60627712 4.64813222 4.85505901 ... 0.         5.92848015 3.11754091]
 [4.33123192 1.28134574 1.099363   ... 5.92848015 0.         2.82247675]
 [1.54798574 1.5529183  1.73850483 ... 3.11754091 2.82247675 0.        ]]
